#!/bin/sh
# initramfs init

. /bin/init_functions
do_init_prepare

echo "=========================================="
echo " Welcome to the ZPod OS !"
echo "=========================================="

do_init_rootfs_prepare;

if [ "${rmode}" = "zpod" ];  then
    echo "[*] Starting ZPod..."
    do_boot_normal
else    
    # check maybe install
    . /sbin/init_install || exec /bin/busybox sh

    sync && (eject /dev/sr0 ;eject /dev/cdrom ; eject -s /dev/sr0 ; eject -s /dev/cdrom) || true
    do_reboot
fi
