#!/bin/bash

# Exit immediately if a command exits with a non-zero status.
set -e 

# --- Configuration ---
export INSTALLER_URL="https://github.com/key2p/linux/releases/download/apod%2Fv6.19-edge_cloud/zpodv3.tar.gz"
export BOOT_DIR="/boot"
export CLEAN_DATA="n"

while [[ $# -ge 1 ]]; do
    case $1 in
    -b|--boot)
        shift
        BOOT_DIR="$1"
        shift
        ;;
    -u|--url)
        shift
        INSTALLER_URL="$1"
        shift
        ;;
    -c|--clean)
        shift
        CLEAN_DATA="y"
        ;;
    *)
      echo "Unknown option: "
      exit 1;
        ;;
    esac
done

# Configuration end

export GRUB_DEFAULT_FILE="$BOOT_DIR/grub/grub.cfg"

CONFIG_FILE="$BOOT_DIR/zpod_config.conf"
GRUB_OPT=""

# --- Logging functions ---
log_info() {
    echo -e "\033[0;34m[INFO]\033[0m $1"
}

log_success() {
    echo -e "\033[0;32m[SUCCESS]\033[0m $1"
}

log_warn() {
    echo -e "\033[0;33m[WARNING]\033[0m $1"
}

log_error() {
    echo -e "\033[0;31m[ERROR]\033[0m $1" >&2
    exit 1
}

# check root & grub conf
[[ "$EUID" -ne '0' ]] && log_error "Error:This script must be run as root!"

if [ ! -f "$GRUB_DEFAULT_FILE" ]; then
  log_error "$GRUB_DEFAULT_FILE Not Found grub.\n"
fi

# Gathers network information from the live system.
gather_network_info() {
    log_info "Gathering network configuration..."
    
    IFACE=$(ip route | grep '^default' | awk '{print $5}' | head -n 1)
    if [ -z "$IFACE" ]; then
        log_error "Could not determine the primary network interface. Cannot proceed."
    fi
    IFACE_MAC=$(cat /sys/class/net/"$IFACE"/address)
    log_info "Detected primary network interface: $IFACE@$IFACE_MAC"
    
    # IPv4
    IPV4_ADDR=$(ip -4 addr show dev "$IFACE" | grep -oP 'inet \K[\d\./]+' | head -n 1)
    IPV4_GATEWAY=$(ip -4 route show default | grep -oP 'via \K[\d\.]+' | head -n 1)

    # IPv6 (optional)
    IPV6_ADDR=$(ip -6 addr show dev "$IFACE" scope global | grep -oP 'inet6 \K[a-f0-9:/]+' | head -n 1)
    IPV6_GATEWAY=$(ip -6 route show default | grep -oP 'via \K[a-f0-9:]+' | head -n 1)
    
    # DNS
    DNS_SERVERS=$(grep '^nameserver' /etc/resolv.conf | grep -v '127.0' | awk '{print $2}' | tr '\n' ' ')
}

# Gathers information about swap devices, looking for whole disks.
gather_swap_info() {
    log_info "Gathering swap information..."
    SWAP_DISK=""
    # Get active swap devices
    SWAP_DEVICES=$(swapon --show=NAME --noheadings)
    for dev in $SWAP_DEVICES; do
        # Check if the device is a whole disk (e.g., /dev/sda) vs a partition (/dev/sda1)
        DEV_NAME=$(basename "$dev")
        DEV_TYPE=$(lsblk -o NAME,TYPE -nl | grep "^${DEV_NAME} " | awk '{print $2}')
        if [ "$DEV_TYPE" = "disk" ]; then
            SWAP_DISK="$dev"
            log_info "Found swap on whole disk: $SWAP_DISK. This can be re-created by the installer."
            # We only support one for now, so break on first find
            break
        fi
    done

    if [ -z "$SWAP_DISK" ]; then
        log_info "No swap configured on a whole disk. Skipping."
    fi
}

# Creates the configuration file for the installer.
generate_config() {
    log_info "Generating installer configuration file at $CONFIG_FILE..."
    
    hostname=$(hostname)
    cat > "$CONFIG_FILE" << EOF
# ZPod Installer Configuration
# This file was auto-generated by dd.sh and will be used by the installer.

#[system]
hostname="$hostname"
ssh_authorized_key="$SSH_KEY_B64"

#[network]
interface="$IFACE@$IFACE_MAC"
ipv4_address="${IPV4_ADDR}"
ipv4_gateway="$IPV4_GATEWAY"
ipv6_address="${IPV6_ADDR}"
ipv6_gateway="$IPV6_GATEWAY"
dns_servers="$DNS_SERVERS"

#[storage]
# The installer can optionally re-create a swap on this specified disk.
# Only whole disks are supported (e.g., /dev/sdb, not /dev/sdb1).
swap_disk="$SWAP_DISK"
EOF

    log_success "Configuration file created."
}

# Downloads and extracts the installer files.
download_installer() {
    log_info "Downloading installer from $INSTALLER_URL..."
    
    if command -v "curl" &> /dev/null; then
        curl -k -L -o "/dev/shm/installer.tar.gz" "$INSTALLER_URL" || log_error "Download failed using curl."
    elif command -v "wget" &> /dev/null; then
        wget --no-check-certificate -O "/dev/shm/installer.tar.gz" "$INSTALLER_URL" || log_error "Download failed using wget."
    else
        log_error "Neither curl nor wget is available. Cannot download files."
    fi

    log_info "Extracting installer files ${BOOT_DIR} ..."
    tar -zxf "/dev/shm/installer.tar.gz" -C "$BOOT_DIR"  || log_error "Failed to ungz the installer package."
    rm -f "/dev/shm/installer.tar.gz" || true
    
    [ "$CLEAN_DATA" != "y" ] && rm -f "$BOOT_DIR/disk.img.gz" || true
    
    if [ ! -f "$BOOT_DIR/zpod-vmlinuz" ] || [ ! -f "$BOOT_DIR/zpod-initrd" ]; then
        log_error "The tar.gz file must contain 'zpod-vmlinuz' and 'zpod-initrd' files."
    fi

    log_success "Installer files are ready."
}

build_grub_opt() {
    if [ "$CLEAN_DATA" != "y" ]; then
        GRUB_OPT="${GRUB_OPT} rmode=zpod"

        ROOT_DEV=$(df -h   | awk '$NF=="/"{printf "%s", $1}')
        ROOT_UUID=$(blkid -s UUID -o value "$ROOT_DEV")

        echo "save root ${ROOT_DEV} uuid ${ROOT_UUID} to grub"
        GRUB_OPT="${GRUB_OPT} root=UUID=${ROOT_UUID}"
    fi
}


# Configures GRUB to boot the installer on the next reboot.
setup_grub() {   
    # 1. Set the new entry as default for the next boot
    log_info "Backing up $GRUB_DEFAULT_FILE to $GRUB_DEFAULT_FILE.zpod.bak..."
    cp "$GRUB_DEFAULT_FILE" "$GRUB_DEFAULT_FILE.zpod.bak" || true

    ZPOD_NOT_EXIST=$(grep ZPod $GRUB_DEFAULT_FILE || echo 'not_found');
    if [ "$ZPOD_NOT_EXIST" = "not_found" ]; then
        build_grub_opt

        sed -i '
0,/--class os/ {
    /--class os/ {
        i\
set timeout=3\
set default=0\
menuentry 'ZPod' --class gnu-linux --class gnu --class os {\
  linux xxboot/zpod-vmlinuz net.ifnames=0 biosdevname=0 xxxopt ro mitigations=off selinux=0 quiet cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1\
  initrd xxboot/zpod-initrd\
}
    }
}' "$GRUB_DEFAULT_FILE"

        # 使用 @ 作为分隔符, 避免变量中的 / 被特殊处理
        sed -i "s@xxboot@${BOOT_DIR}@g" $GRUB_DEFAULT_FILE 
        sed -i "s@xxxopt@${GRUB_OPT}@g" $GRUB_DEFAULT_FILE 
    fi

    log_success "GRUB has been configured to boot the ZPod by default on next reboot."
}

# --- Main execution ---
main() {  
    log_info "--- ZPod Installer Setup ---"
    log_info "This script will download the ZPod installer and configure your system to boot into it."
    log_warn "The current operating system on this machine will be REPLACED."
    
    gather_network_info
    gather_swap_info
       
    generate_config
    download_installer
    setup_grub

    echo
    log_success "All done! The system is now configured to launch the ZPod installer."
    log_warn "Please reboot your system to begin the installation process."
}

main "$@"
