#!/bin/bash

set -e
set -u
set -o pipefail

DISTS="13
"
LATEST="13"
BASENAME=key2p/debian

if [ -n "${DOCKER_PASSWORD:-}" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
fi

ENABLE_DOCKER_CONTENT_TRUST=0
if [ -n "${DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE:-}" ] && [ -n "${DOCKER_CONTENT_TRUST_REPOSITORY_KEY:-}" ]; then
    tmpdir=$(mktemp -d)
    (cd "${tmpdir}" && bash -c 'echo -n "${DOCKER_CONTENT_TRUST_REPOSITORY_KEY}" | base64 -d > key')
    chmod 400 "${tmpdir}/key"
    docker trust key load "${tmpdir}/key"
    rm -rf "${tmpdir}"
    export ENABLE_DOCKER_CONTENT_TRUST=1
fi

push() {
    local dist="$1"
    DOCKER_CONTENT_TRUST=${ENABLE_DOCKER_CONTENT_TRUST} docker push "${BASENAME}:${dist}"
}

for DIST in $DISTS; do
    push "$DIST"
done

docker tag "${BASENAME}:${LATEST}" "${BASENAME}:latest"

push latest
